name: Build and Push Docker Image
on:
 push:
   branches:
     - main  # Trigger the workflow on push to main branch
jobs:
 build:
   runs-on: ubuntu-latest
   steps:
     # Step 1: Check out the code from your GitHub repository
     - name: Checkout code
       uses: actions/checkout@v2
     # Step 2: Set up Docker Buildx to build Docker images
     - name: Set up Docker Buildx
       uses: docker/setup-buildx-action@v2
     # Step 3: Log in to Docker Hub using GitHub Secrets
     - name: Log in to Docker Hub
       run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
     # Step 4: Build the Docker image and tag it with the commit SHA
     - name: Build Docker image
       run: docker build -t ${{ secrets.DOCKER_USERNAME }}/my-web-app:${{ github.sha }} .
     # Step 5: Push the Docker image to Docker Hub
     - name: Push Docker image
       run: docker push ${{ secrets.DOCKER_USERNAME }}/my-web-app:${{ github.sha }}